[1]
entry = "python"
ext = "py"

[2]
entry = "nodejs"
ext = "js"

[3]
entry = "bash"
ext = "sh"

[4]
entry = "perl"
ext = "pl"

[5]
entry = "lua"
ext = "lua"

[6]
entry = "ruby"
ext = "rb"

[7]
entry = "c"
ext = "c"

[8]
entry = "cpp"
ext = "cpp"

[9]
entry = "rust"
ext = "rs"

[10]
entry = "fortran"
ext = "f90"

[11]
entry = "haskell"
ext = "hs"

[12]
entry = "java"
ext = "java"

[13]
entry = "go"
ext = "go"

[14]
entry = "typescript"
ext = "ts"

[15]
entry = "clisp"
ext = "lisp"

[16]
entry = "racket"
ext = "rkt"

[17]
entry = "crystal"
ext = "cr"

[18]
entry = "clojure"
ext = "clj"

[19]
entry = "nasm"
ext = "asm"

[20]
entry = "zig"
ext = "zig"

[21]
entry = "nim"
ext = "nim"

[22]
entry = "d"
ext = "d"

[23]
entry = "csharp"
ext = "cs"

[24]
entry = "rscript"
ext = "r"

[25]
entry = "dart"
ext = "dart"

[26]
entry = "vb"
ext = "vb"

[27]
entry = "fsharp"
ext = "fs"
