version: "3"

tasks:
  run:
    cmds:
      - ./bin/whipcode {{.CLI_ARGS}}

    silent: true

  build:
    cmds:
      - go build -o ./bin/whipcode

  build-images:
    cmds:
      - ./bin/whipcode --build-images

  rebuild-images:
    cmds:
      - podman rmi --force $(podman images -q "whipcode-*" | uniq)
      - task build-images

  clean:
    cmds:
      - rm -rf bin/*

  all:
    cmds:
      - task clean
      - task build
      - task build-images

  update:
    cmds:
      - git pull
      - task all

  config-init:
    cmds:
      - cp config.default.toml config.toml
      - ${EDITOR:-vim} config.toml

  key:
    cmds:
      - ./bin/whipcode --gen-key

  test:
    cmds:
      - ./bin/whipcode --self-test

  systemd-install:
    cmds:
      - mkdir -p $HOME/.config/systemd/user/
      - cp systemd/whipcode.service $HOME/.config/systemd/user/
      - sed -i "s|/path/to/whipcode|$(pwd)|g" $HOME/.config/systemd/user/whipcode.service
      - systemctl --user daemon-reload
      - systemctl --user enable --now whipcode
      - sudo loginctl enable-linger $USER

  status:
    cmds:
      - systemctl --user status whipcode

  logs:
    cmds:
      - journalctl --user -x -e _PID=$(systemctl --user show --property MainPID whipcode | cut -d= -f2)

  logs-full:
    cmds:
      - journalctl --user -x -e -u whipcode
