version: "3"

tasks:
  update:
    cmds:
      - git pull
      - task all

  build:
    cmds:
      - go build -o ./bin/whipcode

  build-images:
    cmds:
      - bash scripts/images.sh

  rebuild-images:
    cmds:
      - podman rmi --force $(podman images -q "whipcode-*" | uniq)
      - task build-images

  clean:
    cmds:
      - rm -rf bin/*

  all:
    cmds:
      - task clean
      - task build
      - task build-images

  key:
    cmds:
      - echo -n "{{.CLI_ARGS}}" | bash scripts/masterkey.sh

  run:
    cmds:
      - ./bin/whipcode {{.CLI_ARGS}}

    silent: true

  test:
    cmds:
      - bash scripts/tests.sh
