[1]  # python
test = '''
print("Success!")
'''

[2]  # javascript
test = '''
console.log("Success!");
'''

[3]  # bash
test = '''
echo "Success!"
'''

[4]  # perl
test = '''
print "Success!";
'''

[5]  # lua
test = '''
print("Success!")
'''

[6]  # ruby
test = '''
puts "Success!"
'''

[7]  # c
test = '''
#include <stdio.h>
int main() {
   printf("Success!");
   return 0;
}
'''

[8]  # c++
test = '''
#include <iostream>
int main() {
   std::cout << "Success!";
   return 0;
}
'''

[9]  # rust
test = '''
fn main() {
    println!("Success!");
}
'''

[10]  # fortran
test = '''
program hello
 print *, "Success!"
end program hello
'''

[11]  # haskell
test = '''
main = putStrLn "Success!"
'''

[12]  # java
test = '''
public class HelloWorld {
   public static void main(String[] args) {
       System.out.println("Success!");
   }
}
'''

[13]  # go
test = '''
package main
import "fmt"
func main() {
  fmt.Println("Success!")
}
'''

[14]  # typescript
test = '''
let message: string = "Success!";
console.log(message);
'''

[15]  # common lisp
test = '''
(write-line "Success!")
'''

[16]  # racket
test = '''
#lang racket
"Success!"
'''

[17]  # crystal
test = '''
puts "Success!"
'''

[18]  # clojure
test = '''
(println "Success!")
'''

[19]  # nasm
test = '''
section .text
global _start
_start:
   mov edx, len
   mov ecx, msg
   mov ebx, 1
   mov eax, 4
   int 0x80
   mov eax, 1
   int 0x80
section .data
msg db "Success!", 0xa
len equ $ - msg
'''

[20]  # zig
test = '''
const std = @import("std");
pub fn main() !void {
   std.io.getStdOut().writeAll("Success!") catch unreachable;
}
'''

[21]  # nim
test = '''
echo "Success!"
'''

[22]  # d
test = '''
import std.stdio;
void main() {
   writeln("Success!");
}
'''

[23]  # c#
test = '''
Console.WriteLine("Success!");
'''

[24]  # rscript
test = '''
print("Success!")
'''

[25]  # dart
test = '''
void main() {
   print("Success!");
}
'''

[26]  # vb.net
test = '''
Module Program
    Sub Main()
         Console.WriteLine("Success!")
    End Sub
End Module
'''

[27]  # f#
test = '''
printfn "Success!"
'''

[28]  # php
test = '''
<?php echo "Success!";
'''
